### ISSUE TITLE
Add in initial implementation of schedule

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/ruhacks-2018-website-frontend#10]
We'll need to add in schedule before the event starts. This will include meal times, events, and workshops. We'll be referring to the finalized schedule.

**Comment by ktsuench** [comment]
@streacy any ideas on how you're going to show the schedule? Anything is fine for now, best get started thinking about it.

**Comment by streacy** [comment]
@ktsuench yea im going to do it like like U of T Hacks https://uofthacks.com/

**Comment by ktsuench** [comment]
Sounds good, we'll update you with the schedule details soon so you can get started.

**Comment by ktsuench** [comment]
refer to #12
