### ISSUE TITLE
Add in missing JS files

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/ruhacks-2018-website-frontend#2]
@streacy can you add in the missing js files for the index?

**Comment by streacy** [comment]
I added in js to make the nav bar responsive on mobile and I changed the colour of h2 to white

**Comment by ktsuench** [comment]
I had to make some modifications to the navbar css and html to get it working again. Anyways this solves the js issue kind of. There are some performance issues we might have to look into. More on that later.
