### ISSUE TITLE
Add in initial list of sponsors

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/ruhacks-2018-website-frontend#3]
We'll need to start adding in sponsor logos soon. Updates coming...

**Comment by ktsuench** [comment]
@streacy can you get started on adding in the sponsor/partner images? Start with HackerEarth (_looks like I didn't add it in, will do it later today_) and RSS. @jas2996 and @Stev-enD should RESS/EE department logos go up to?

I'll get you the MLH logo (_and maybe GitHub logo?_) later.

**Comment by streacy** [comment]
@ktsuench where do I get the sponsor images from?

**Comment by ktsuench** [comment]
I forgot to mention they are in the `sponsors_partners` directory under `img`. The HackerEarth one isn't there yet I somehow didn't have it committed. I'll do that later today.

**Comment by ktsuench** [comment]
I added in HackerEarth, MLH, and Github logos to the `img/sponsors_partners` directory.

**Comment by ktsuench** [comment]
Rogers logo has been added to the `img/sponsors_partners` directory.

**Comment by ktsuench** [comment]
@streacy Can we switch the sponsors and the prize sections so that the sponsors section with the logos are easier to see.
